import Head from 'next/head';
import Player from './Player';
import './globals.css';

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <Player />
      </main>
    </div>
  );
}
